config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'

  get 'comments/destroy'

  get 'posts/index'

    get "log_out" => "sessions#destroy", :as => "log_out"
    get "log_in" => "sessions#new", :as => "log_in"
    get "sign_up" => "users#new", :as => "sign_up"
    root :to => "sessions#new"
    resources :users
    resources :sessions
    resources :posts
    resources :friendships
    resources :comments, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Shared::Callbacks
  include ActsAsCommentable::Comment
  include Mention

  belongs_to :commentable, polymorphic: true, counter_cache: true
  belongs_to :post
  belongs_to :user
  default_scope -> { order('created_at DESC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  # acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  include PublicActivity::Model
  tracked only: [:create], owner: proc { |_controller, model| model.user }

  validates_presence_of :comment
  validates_presence_of :commentable
  validates_presence_of :user

  auto_html_for :comment do
    image
    youtube(width: 400, height: 250, autoplay: true)
    link target: '_blank', rel: 'nofollow'
    simple_format
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :friend, :class_name => "User"
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :comments
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    helper_method :current_user

    private

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable, only: :create
  respond_to :js
  def create
  	 @comment = @commentable.comments.new do |comment|
      comment.comment = params[:comment_text]
      comment.user = current_user
    end
    @comment.save
  end

  def destroy
  	@comment = current_user.comments.find(params[:id])
    @comment_id = params[:id]
    @comment.destroy
  end
  private
  def find_commentable
    @commentable_type = params[:commentable_type].classify
    @commentable = @commentable_type.constantize.find(params[:commentable_id])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	 def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice] = "Added friend."
      redirect_to root_url
    else
      flash[:error] = "Error occurred when adding friend."
      redirect_to root_url
    end
  end
  
  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] = "Successfully destroyed friendship."
    redirect_to root_url
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    respond_to do |format|
      format.html
    end
  end
  def show
  @post = Post.find(params[:id])
  @comment = Comment.find(params[:id])
  authorize @comment
  @comments = @post.comments
  end

  def create
    @post = Post.create(:message => params[:message])
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path }
      else
        flash[:notice] = "Message failed to save."
        format.html { redirect_to posts_path }
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.authenticate(params[:email], params[:password])
        if user
            session[:user_id] = user.id
            redirect_to posts_url
        else
            flash.now.alert = "Invalid email or password"
            render "new"
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_url, :notice => "Logged out!"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
    @users = User.all
    end
    def show
    @user = current_user
    end
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to root_url, :notice => "Signed up!"
        else
            render "new"
        end
    end
    
    private
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
  <div class="info">
    <%= render 'shared/avatar', user: comment.user %>
    <h4 class="name"><%= link_to comment.user.name, user_path(comment.user) %></h4>
  </div>
  <div class="content">
    <div class="row">
      <span class="text"><%= comment.comment_html %></span>
    </div>
    <div class="pull-right">
      <% if belongs_to_user?(comment) %>
        <%= link_to comment_path(comment), method: :delete, class: 'btn btn-danger btn-sm', remote: true do %>
          <% fa_icon 'trash' %>
        <% end %>
      <% end %>
    </div>
  </div>
  <br>
  <hr>
</div>

app/views/comments/_form.html.erb
<div id="mentionable-data" data-content="<%= mentionable_user_path(current_user) %>"></div>
<%= form_tag comments_path(commentable_type: commentable.class.to_s, commentable_id: commentable.id), id: 'new_comment', method: :post, remote: true do %>
  <div class="form-group">
    <div id="comment-text" contenteditable="true" class="editable form-control input-mentionable" placeholder="Enter Comment"></div>
    <%= hidden_field_tag :comment_text, nil, placeholder: 'Enter Comment', class: 'form-control input-mentionable' %>
  </div>
  <%= submit_tag :comment, class: 'btn btn-primary' %>
<% end %>

app/views/comments/create.js.erb
$("#<%= @commentable_type.downcase %>-<%= @commentable.id %> .comments").prepend("<%=j render(@comment) %>");
$("#comment_text").val("");

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Sociapp</title>
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

 <%= yield %>
</body>
</html>

app/views/posts/_message_form.html.erb
<% if current_user %>
<form class="message">
	<%= form_tag(:controller => "posts", :action => "create") do %>
	<div class="panel panel-default">
		<div class="panel-body">
			<%= label_tag(:message, "What are you doing?") %><br />
			<%= text_area_tag(:message, nil, :size => "60x2") %><br /> 
    		<div style="float: right;"><%= submit_tag("Update") %></div>
		</div>
	</div>
  <% end %>
</form>
 <% end %>

app/views/posts/_post.html.erb
<div class="panel panel-default">
	<div class="panel-body">
	<% if current_user %>
    <p><b>Posted <%= time_ago_in_words(post.created_at) %> ago by <%=  %> </b></p>
    <p><%= post.message %></p>
<% end %>
	</div>
</div>

app/views/posts/index.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
<!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
      <% if current_user %>
    <a class="navbar-brand" href="#"><%= current_user.email %>.</a>
  </div>

<!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Explore</a></li>
      <li><a href="#">Messenger</a></li>
    </ul>
  <form class="navbar-form navbar-left" role="search">
    <div class="form-group">
      <input type="text" class="form-control" placeholder="Search">
    </div>
      <button type="submit" class="btn btn-default">Submit</button>
  </form>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Log out", log_out_path %></li>
    </ul>
      <% else %>
    <ul>
      <li>
      <%= link_to "Sign up", sign_up_path %>
      </li>
      </ul>
      <% end %>
      <button type="button" class="btn btn-primary" style="margin-top: 10px; float: right;">Tweet</button>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>
<div class="container">
  <div class="row">
    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
      
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= render :partial => "message_form" %>
	  <%= render :partial => @posts %>
     
    </div>
    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
      <%= link_to "Make Friends", users_path %> <br>
      <%= link_to "My Friends", { :controller => "users", :action => "show", :id => current_user } %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
  <% @users.each do |user| %>
      <% if user.email != current_user.email %>
        <%= h user.email %>
        <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %> <br>
      <% end %>
    
    
  <% end %>

app/views/users/new.html.erb
<h1 style="text-align: center;">Sign Up</h1>
<form class="register">
  <%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button" style="float: right;"><%= f.submit %></p>
<% end %>
</form>